### ISSUE TITLE
Ich wurde aus der Ilias Gruppe zur Funktionalanalysis rausgeworfen?

### ISSUE THREAD

**Issue by Nick-Seinsche** [tschmidtchemnitz/Funktionalanalysis_SS2020_UniversitaetFreiburg#1]
Ich bin vor einigen Tagen beigetreten. Habe nun keinen Zugriff mehr darauf (über den Link) und kann die Gruppe auch nicht mehr direkt im Ilias finden.

![ss+(2020-04-28+at+04 27 23)](https://user-images.githubusercontent.com/18193816/80499375-31e8c380-896d-11ea-86b9-3ed01a6a7a44.png)

**Comment by tschmidtfreiburg** [comment]
Der Link sollte eigentlich funktionieren:

https://ilias.uni-freiburg.de/goto.php?target=crs_1538694&client_id=unifreiburg

(siehe Homepage)

oder ?

**Comment by Nick-Seinsche** [comment]
Wenn ich den Link anklicke bekomme ich die Fehlermeldung:

"**Sie haben keine Berechtigung, auf das Objekt 'Funktionalanalysis: Vorlesung (-)' zuzugreifen."**

(und werde auf die Hauptseite von Ilias weitergeleitet)

Und das, obwohl ich vor ein paar Tagen auch eine Bestätigungsmail erhalten habe, dass ich der Gruppe beigetreten bin. In der Mail steht auch der selbe [Link](https://ilias.uni-freiburg.de/goto.php?target=crs_1538694&client_id=unifreiburg) wie auf der Vorlesungsseite. Auch wenn ich versuche den Kurs manuell zu suchen; also über

[**Magazin >> Lehrveranstaltungen im SoSe 2020 >> Fakultät für Mathematik und Physik >> Mathematik**](https://ilias.uni-freiburg.de/ilias.php?ref_id=1441320&cmd=frameset&cmdClass=ilrepositorygui&cmdNode=yc&baseClass=ilRepositoryGUI)

finde ich den Kurs nicht mehr.

**Comment by tschmidtfreiburg** [comment]
funktionierts jetzt ? Habe den Kurs _ONLINE_ geschaltet :D

**Comment by Nick-Seinsche** [comment]
Ja jetzt funktioniert es ;)

**Comment by mark7980** [comment]
Hallo Thorsten,Alles klar, perfekt! Das hat bei mir auch schon fragen aufgeworfen, weil die Tutoren nicht reinkamen. Aber jetzt klappt es ja!Übrigens, die Zoom Lizenzen haben wir nicht bekommen. Laut Prof. Soergel sollen wir ein anderes, kostenloses System benutzen. Ich schau mir das morgen an und melde mich nochmal, falls das nicht gut ist.GrüßeMarcAm 28.04.2020 20:55 schrieb Thorsten Schmidt <notifications@github.com>:
Closed #1.
